# Generated by Django 3.2 on 2023-02-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField(max_length=200, null=True)),
                ('img', models.ImageField(default='cat_images/default.jpg', upload_to='cat_images')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainer', models.CharField(max_length=150)),
                ('Course_Fee', models.FloatField(max_length=150)),
                ('Available_Seats', models.CharField(max_length=150)),
                ('Schedule', models.CharField(max_length=150)),
                ('desc', models.TextField(max_length=400)),
            ],
        ),
    ]
